/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApartmentsIndexRouteImport } from './routes/apartments.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ApartmentsSlugRouteImport } from './routes/apartments.$slug'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminCmsRouteImport } from './routes/admin.cms'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminApartmentsRouteImport } from './routes/admin.apartments'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApartmentsIndexRoute = ApartmentsIndexRouteImport.update({
  id: '/apartments/',
  path: '/apartments/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ApartmentsSlugRoute = ApartmentsSlugRouteImport.update({
  id: '/apartments/$slug',
  path: '/apartments/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsRoute = AdminCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApartmentsRoute = AdminApartmentsRouteImport.update({
  id: '/apartments',
  path: '/apartments',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/payment': typeof PaymentRoute
  '/signup': typeof SignupRoute
  '/admin/apartments': typeof AdminApartmentsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/users': typeof AdminUsersRoute
  '/apartments/$slug': typeof ApartmentsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/apartments/': typeof ApartmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/payment': typeof PaymentRoute
  '/signup': typeof SignupRoute
  '/admin/apartments': typeof AdminApartmentsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/users': typeof AdminUsersRoute
  '/apartments/$slug': typeof ApartmentsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/apartments': typeof ApartmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/payment': typeof PaymentRoute
  '/signup': typeof SignupRoute
  '/admin/apartments': typeof AdminApartmentsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/users': typeof AdminUsersRoute
  '/apartments/$slug': typeof ApartmentsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/apartments/': typeof ApartmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/booking'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/payment'
    | '/signup'
    | '/admin/apartments'
    | '/admin/bookings'
    | '/admin/cms'
    | '/admin/users'
    | '/apartments/$slug'
    | '/admin/'
    | '/apartments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/booking'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/payment'
    | '/signup'
    | '/admin/apartments'
    | '/admin/bookings'
    | '/admin/cms'
    | '/admin/users'
    | '/apartments/$slug'
    | '/admin'
    | '/apartments'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/booking'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/payment'
    | '/signup'
    | '/admin/apartments'
    | '/admin/bookings'
    | '/admin/cms'
    | '/admin/users'
    | '/apartments/$slug'
    | '/admin/'
    | '/apartments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BookingRoute: typeof BookingRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PaymentRoute: typeof PaymentRoute
  SignupRoute: typeof SignupRoute
  ApartmentsSlugRoute: typeof ApartmentsSlugRoute
  ApartmentsIndexRoute: typeof ApartmentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apartments/': {
      id: '/apartments/'
      path: '/apartments'
      fullPath: '/apartments/'
      preLoaderRoute: typeof ApartmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/apartments/$slug': {
      id: '/apartments/$slug'
      path: '/apartments/$slug'
      fullPath: '/apartments/$slug'
      preLoaderRoute: typeof ApartmentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms': {
      id: '/admin/cms'
      path: '/cms'
      fullPath: '/admin/cms'
      preLoaderRoute: typeof AdminCmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/apartments': {
      id: '/admin/apartments'
      path: '/apartments'
      fullPath: '/admin/apartments'
      preLoaderRoute: typeof AdminApartmentsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminApartmentsRoute: typeof AdminApartmentsRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCmsRoute: typeof AdminCmsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApartmentsRoute: AdminApartmentsRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCmsRoute: AdminCmsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BookingRoute: BookingRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PaymentRoute: PaymentRoute,
  SignupRoute: SignupRoute,
  ApartmentsSlugRoute: ApartmentsSlugRoute,
  ApartmentsIndexRoute: ApartmentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
